name: Sync with upstream

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync with upstream
      run: |
        git remote add upstream https://github.com/AprilNEA/ChatGPT-Admin-Web.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push origin master
